// 水生植物补充清单(不在 Excel 9 张表里,单独补充,由 import-excel.mjs 合并)
// 字段参考 src/data 顶层 schema;categoryOf 依赖 designLayer / rawNotes 判定为「水生植物」
export const AQUATIC_PLANTS = [
  {
    chineseName: '三白草',
    latinName: 'Saururus chinensis',
    genus: '三白草属',
    family: '三白草科',
    order: '胡椒目',
    designLayer: '水生植物',
    sun: 'part shade',
    water: 'wet',
    flowerColor: '白',
    bloomSeason: '夏',
    leafForm: '心形叶',
    reliability: '强健',
    rawNotes: '湿生水生植物，喜浅水，可用作水边及池畔点缀。',
  },
  {
    chineseName: '白花千屈菜',
    latinName: 'Lythrum salicaria f. alba',
    genus: '千屈菜属',
    family: '千屈菜科',
    order: '桃金娘目',
    designLayer: '水生植物',
    sun: 'full sun',
    water: 'wet',
    flowerColor: '白',
    bloomSeason: '夏-秋',
    leafForm: '细长叶',
    reliability: '强健',
    rawNotes: '湿生水生植物，挺拔穗状白花，宜水边丛植。',
  },
  {
    chineseName: '溪荪',
    latinName: 'Iris sanguinea',
    genus: '鸢尾属',
    family: '鸢尾科',
    order: '天门冬目',
    designLayer: '水生植物',
    sun: 'full sun',
    water: 'wet',
    flowerColor: '蓝紫',
    bloomSeason: '春-夏',
    leafForm: '剑形叶',
    reliability: '强健',
    rawNotes: '湿生水生植物，喜水边及浅水，剑形叶，花挺拔。',
  },
  {
    chineseName: '泽珍珠菜',
    latinName: 'Lysimachia candida',
    genus: '珍珠菜属',
    family: '报春花科',
    order: '杜鹃花目',
    designLayer: '水生植物',
    sun: 'part shade',
    water: 'wet',
    flowerColor: '白',
    bloomSeason: '春-夏',
    leafForm: '卵形叶',
    rawNotes: '湿生水生植物，喜水边，株型轻盈。',
  },
  {
    chineseName: '矮生苦草',
    latinName: 'Vallisneria nana',
    genus: '苦草属',
    family: '水鳖科',
    order: '泽泻目',
    designLayer: '水生植物',
    sun: 'full sun',
    water: 'wet',
    leafForm: '带状叶',
    rawNotes: '沉水水生植物，矮生，适合浅水池或水景。',
  },
  {
    chineseName: '金鱼藻',
    latinName: 'Ceratophyllum demersum',
    genus: '金鱼藻属',
    family: '金鱼藻科',
    order: '金鱼藻目',
    designLayer: '水生植物',
    sun: 'part shade',
    water: 'wet',
    leafForm: '羽状细裂叶',
    rawNotes: '沉水水生植物，无根，可净化水质。',
  },
  {
    chineseName: '慈菇',
    latinName: 'Sagittaria sagittifolia',
    genus: '慈姑属',
    family: '泽泻科',
    order: '泽泻目',
    designLayer: '水生植物',
    sun: 'full sun',
    water: 'wet',
    flowerColor: '白',
    bloomSeason: '夏',
    leafForm: '箭形叶',
    reliability: '强健',
    rawNotes: '挺水水生植物，箭形叶，宜水边或浅水种植。',
  },
  {
    chineseName: '泽泻',
    latinName: 'Alisma plantago-aquatica',
    genus: '泽泻属',
    family: '泽泻科',
    order: '泽泻目',
    designLayer: '水生植物',
    sun: 'full sun',
    water: 'wet',
    flowerColor: '白',
    bloomSeason: '夏',
    leafForm: '卵形叶',
    reliability: '强健',
    rawNotes: '挺水水生植物，叶似车前，花淡白，宜浅水。',
  },
];
